# Generated by Django 5.0.3 on 2024-04-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_is_deleted_subjects_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='user',
        ),
    ]
