# Generated by Django 5.0.3 on 2024-04-04 06:58

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_name_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_upload_path),
        ),
    ]
